# Generated by Django 2.2 on 2021-04-03 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userentity',
            name='last_login',
        ),
    ]
