# Generated by Django 2.2 on 2021-04-03 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postentity',
            name='dislike',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='postentity',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
