# Generated by Django 2.2 on 2021-04-03 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_commententity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postentity',
            name='dislike',
        ),
        migrations.RemoveField(
            model_name='postentity',
            name='like',
        ),
    ]
