# Generated by Django 2.2 on 2021-04-03 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_trendentity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trendentity',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_trends', to='blog.CommentEntity'),
        ),
    ]
